language: android
sudo: required
env:
  global:
  - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

jdk:
- oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - android-21
  - sys-img-armeabi-v7a-google_apis-21

before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a --tag google_apis
- emulator -avd test -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- ./gradlew build connectedCheck